// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MuWdoKL-ugC9QIfeFUWvxs3YSArzEyg',
    appId: '1:31766616131:web:e7888a4421eb05445d9cf6',
    messagingSenderId: '31766616131',
    projectId: 'tetherus-0',
    authDomain: 'tetherus-0.firebaseapp.com',
    storageBucket: 'tetherus-0.firebasestorage.app',
    measurementId: 'G-WF3GWKTQ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIT14w8wFg3qbKgVCBgWZXPzMq7fGvCyA',
    appId: '1:31766616131:android:59d8a0cfa28743985d9cf6',
    messagingSenderId: '31766616131',
    projectId: 'tetherus-0',
    storageBucket: 'tetherus-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1SFCSLeR3orR-6dMFxSMPku06sSIZP54',
    appId: '1:31766616131:ios:293bf1ed7b97c72a5d9cf6',
    messagingSenderId: '31766616131',
    projectId: 'tetherus-0',
    storageBucket: 'tetherus-0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
